<?php
/*********************************************************************
    api.mcp-file.php

    MCP File Download Controller

    Serves file attachments authenticated via short-lived HMAC tokens
    generated by the MCP server. Allows AI agents to download
    attachments without a browser session.

    vim: expandtab sw=4 ts=4 sts=4:
**********************************************************************/

include_once INCLUDE_DIR.'class.api.php';
include_once INCLUDE_DIR.'class.file.php';

class McpFileApiController extends ApiController {

    function download() {
        if (!isset($_GET['key']) || !isset($_GET['expires']) || !isset($_GET['signature'])) {
            Http::response(400, 'Missing required parameters');
        }

        $key = $_GET['key'];
        $expires = (int) $_GET['expires'];
        $signature = $_GET['signature'];

        if ($expires < time()) {
            Http::response(403, 'Download link has expired');
        }

        $expected = hash_hmac('sha256',
            implode("\n", array($key, $expires, 'mcp-file-download')),
            SECRET_SALT);

        if (!hash_equals($expected, $signature)) {
            Http::response(403, 'Invalid signature');
        }

        $file = AttachmentFile::lookupByHash($key);
        if (!$file) {
            Http::response(404, 'File not found');
        }

        try {
            $disposition = isset($_GET['disposition']) ? $_GET['disposition'] : 'inline';
            $bk = $file->open();
            if ($bk->sendRedirectUrl($disposition, $expires - time()))
                return;

            $ttl = $expires - Misc::gmtime();
            if ($ttl > 0)
                $file->makeCacheable($ttl);

            $type = $file->getType() ?: 'application/octet-stream';
            Http::download($file->getName(), $type, null, $disposition);
            header('Content-Length: '.$file->getSize());
            $file->sendData(false);
        } catch (Exception $ex) {
            Http::response(500, 'Unable to serve file: '.$ex->getMessage());
        }
    }
}
